# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-custom
description: Custom Bazzite mit zsh, enpass und standard apps
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - zsh
        - enpass

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.brave.Browser
          - com.github.Matoking.protontricks
          - com.github.tchx84.Flatseal
          - com.vysp3r.ProtonPlus
          - io.github.DenysMb.Kontainer
          - io.github.flattool.Warehouse
          - org.kde.filelight
          - org.kde.gwenview
          - org.kde.haruna
          - org.kde.kcalc
          - org.kde.okular
          - org.mozilla.firefox
          - org.telegram.desktop

  - type: signing
