name: Build ISO
on:
  workflow_dispatch: # manuell ausloesen
  workflow_run:
    workflows: ["bluebuild"]
    types:
      - completed
    branches:
      - main

jobs:
  build-iso:
    name: Build Bootable ISO
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: Build ISO
        uses: jasonN3/build-container-installer@v1
        id: build
        with:
          arch: x86_64
          image_name: bazzite-custom
          image_repo: ghcr.io/litterboks
          image_tag: latest
          version: 43
          variant: Kinoite
          iso_name: bazzite-custom.iso
          enrollment_password: "universalblue"

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v7
        with:
          name: bazzite-custom-iso
          path: ${{ steps.build.outputs.iso_path }}
          if-no-files-found: error
          retention-days: 14
